config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :tickets, only: :create
    end
  end

  resources :tickets, only: %i[index show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/excavator.rb
# frozen_string_literal: true

class Excavator < ApplicationRecord
  belongs_to :ticket

  def full_address
    [address, city, state, zip].compact.join(', ')
  end
end

app/models/ticket.rb
# frozen_string_literal: true

class Ticket < ApplicationRecord
  has_one :excavator, dependent: :destroy

  enum request_type: {
    normal: 0
  }

  def coordinates
    well_known_text.match(/POLYGON\(\((.*)\)\)/)[1]
  end
end

app/controllers/api/v1/api_controller.rb
# frozen_string_literal: true

class Api::V1::ApiController < ActionController::API
  include SimpleEndpoint::Controller
  include ApplicationEndpoint
end

app/controllers/api/v1/tickets_controller.rb
# frozen_string_literal: true

class Api::V1::TicketsController < Api::V1::ApiController
  def create
    endpoint operation: Api::V1::Tickets::Operation::Create
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found
    render 'errors/not_found'
  end
end

app/controllers/tickets_controller.rb
# frozen_string_literal: true

class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all.includes(:excavator)
  end

  def show
    @ticket = Ticket.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Excavatorr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tickets/index.html.erb
<div><b>Tickets</b></div>

<% @tickets.each do |ticket| %>
  <div>
    <%= ticket.request_number %>
    <%= link_to "Ticket #{ticket.id}", ticket_path(ticket) %>
  </div>
  <hr />
<% end %>

app/views/tickets/show.html.erb
<div>
  Ticket
  <% @ticket.attributes.each do |name, value| %>
    <div>
      <%= "#{name} - #{value}" %>
    </div>
  <% end %>
  <%= hidden_field_tag :coordinates, @ticket.coordinates %>
  <hr / >
  Excavator
  <% @ticket.excavator.attributes.each do |name, value| %>
    <div>
      <%= "#{name} - #{value}" %>
    </div>
  <% end %>
</div>
<div id="map"></div>